name: Diff
on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
      - '.clang-*'

jobs:
  coverage_build:
    name: "Code analysis"
    runs-on: [self-hosted, General, Linux, X64, Debian10]
    env:
      THREADS: 24

    steps:
      - name: Set up repository
        uses: actions/checkout@v2
        with:
          # Number of commits to fetch. `0` indicates all history for all
          # branches and tags. (default: 1)
          fetch-depth: 0

      - name: Build combined ASAN, UBSAN and coverage binaries
        run: |
          # Activate toolchain.
          source /opt/toolchain-v2/activate

          # Initialize dependencies.
          ./init

          cd build
          cmake -DTEST_COVERAGE=ON -DASAN=ON -DUBSAN=ON ..
          make -j$THREADS memgraph__unit

      - name: Run clang-tidy
        run: |
          source /opt/toolchain-v2/activate

          # Restrict clang-tidy results only to the modified parts
          git diff -U0 master... -- src ':!*.hpp' | ./tools/github/clang-tidy/clang-tidy-diff.py -p 1 -j $THREADS -path build | tee ./build/clang_tidy_output.txt

          # Fail if any warning is reported
          ! cat ./build/clang_tidy_output.txt | ./tools/github/clang-tidy/grep_error_lines.sh > /dev/null
      - name: Save compile commands
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: "compile commands"
          path: build/compile_commands.json
