name: "Diff"
concurrency:
  group: ${{ github.head_ref || github.sha }}
  cancel-in-progress: true

on:
  merge_group:
  pull_request:
  workflow_dispatch:
    inputs:
      community_core:
        type: boolean
        default: true
      coverage_core:
        type: boolean
        default: true
      debug_core:
        type: boolean
        default: true
      debug_integration:
        type: boolean
        default: true
      jepsen_core:
        type: boolean
        default: true
      release_core:
        type: boolean
        default: true
      release_benchmark:
        type: boolean
        default: true
      release_e2e:
        type: boolean
        default: true
      release_stress:
        type: boolean
        default: true
      flakiness_runs:
        type: number
        description: "Change this to check for flakiness by running every selected job multiple times. Enter a number between 2 and 20."

jobs:
  DiffSetup:
    runs-on: ubuntu-latest
    outputs:
      run_community_core: ${{ steps.setup.outputs.run_community_core }}
      run_coverage_core: ${{ steps.setup.outputs.run_coverage_core }}
      run_debug_core: ${{ steps.setup.outputs.run_debug_core }}
      run_debug_integration: ${{ steps.setup.outputs.run_debug_integration }}
      run_jepsen_core: ${{ steps.setup.outputs.run_jepsen_core }}
      run_release_core: ${{ steps.setup.outputs.run_release_core }}
      run_release_benchmark: ${{ steps.setup.outputs.run_release_benchmark}}
      run_release_e2e: ${{ steps.setup.outputs.run_release_e2e }}
      run_release_stress: ${{ steps.setup.outputs.run_release_stress }}
      runs: ${{ steps.setup_flakiness.outputs.runs }}
      runs_max_parallel: ${{ steps.setup_flakiness.outputs.runs_max_parallel }}
    env:
      GH_CONTEXT: ${{ toJson(github) }}
      GH_CONTEXT_FILE_NAME: github_context.json
      MAX_PARALLEL: 3
    steps:
      - name: Set up repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Dump GitHub context
        run: echo "$GH_CONTEXT" >> "$GH_CONTEXT_FILE_NAME"
      - name: Set up diff execution
        id: setup
        run: ./tools/diff_setup.py --gh-context-path "$GH_CONTEXT_FILE_NAME" --base-branch "origin/master"
      - name: Set up flakiness runs
        id: setup_flakiness
        run: |
          flakiness_runs=1
          if [[ -n "${{ github.event.inputs.flakiness_runs }}" ]]; then
            if [[ ${{ github.event.inputs.flakiness_runs }} -ge 2 ]] && [[ ${{ github.event.inputs.flakiness_runs }} -le 20 ]]; then
              flakiness_runs=${{ github.event.inputs.flakiness_runs }}
            else
              echo "ERROR: Selected 'flakiness_runs' value is invalid. Please select a value between 2 and 20."
            fi
          fi
          sequence=""
          for i in $(seq 1 $flakiness_runs); do
            sequence+="${i},"
          done
          echo "runs=[${sequence::-1}]" >> $GITHUB_OUTPUT
          echo "runs_max_parallel=$((MAX_PARALLEL))" >> $GITHUB_OUTPUT

  Community:
    needs: DiffSetup
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        run_no: ${{ fromJSON(needs.DiffSetup.outputs.runs) }}
    uses: ./.github/workflows/diff_community.yaml
    with:
      arch: 'amd'
      os: 'debian-11'
      toolchain: 'v5'
      run_core: ${{ needs.DiffSetup.outputs.run_community_core }}
    secrets: inherit

  Coverage:
    needs: DiffSetup
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        run_no: ${{ fromJSON(needs.DiffSetup.outputs.runs) }}
    uses: ./.github/workflows/diff_coverage.yaml
    with:
      arch: 'amd'
      os: 'debian-11'
      toolchain: 'v5'
      run_core: ${{ needs.DiffSetup.outputs.run_coverage_core }}
      run_clang_tidy: ${{ needs.DiffSetup.outputs.run_coverage_core }}
    secrets: inherit

  Debug:
    needs: DiffSetup
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        run_no: ${{ fromJSON(needs.DiffSetup.outputs.runs) }}
    uses: ./.github/workflows/diff_debug.yaml
    with:
      arch: 'amd'
      os: 'debian-11'
      toolchain: 'v5'
      run_core: ${{ needs.DiffSetup.outputs.run_debug_core }}
      run_integration: ${{ needs.DiffSetup.outputs.run_debug_integration }}
    secrets: inherit

  Jepsen:
    needs: DiffSetup
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        run_no: ${{ fromJSON(needs.DiffSetup.outputs.runs) }}
    uses: ./.github/workflows/diff_jepsen.yaml
    with:
      run_core: ${{ needs.DiffSetup.outputs.run_jepsen_core }}
    secrets: inherit

  Release:
    needs: DiffSetup
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        run_no: ${{ fromJSON(needs.DiffSetup.outputs.runs) }}
    uses: ./.github/workflows/diff_release.yaml
    with:
      arch: 'amd'
      os: 'debian-11'
      toolchain: 'v5'
      run_core: ${{ needs.DiffSetup.outputs.run_release_core }}
      run_benchmark: ${{ needs.DiffSetup.outputs.run_release_benchmark }}
      run_e2e: ${{ needs.DiffSetup.outputs.run_release_e2e }}
      run_stress: ${{ needs.DiffSetup.outputs.run_release_stress }}
    secrets: inherit
