name: Run a test
on:
  workflow_call:
    inputs:
      test_name:
        description: Which test will be run?
        required: true
        type: string
      build_name:
        description: Which build type will be used (community, debug, release ...)?
        required: true
        type: string
      threads:
        description: How many threads will be used to build memgraph?
        default: 24
        type: number
      os:
        description: Base image with which os will be used?
        default: debian-10
        type: string
      toolchain_version:
        description: Which toolchain version will be used in the build?
        default: 4
        type: number

env:
  TAG: "memgraph/mgbuilder:${{ github.run_id }}-${{ inputs.build_name }}"
  OS: ${{ inputs.os }}
  TOOLCHAIN_VERSION: ${{ inputs.toolchain_version }}
  THREADS: ${{ inputs.threads }}
  MEMGRAPH_ENTERPRISE_LICENSE: ${{ secrets.MEMGRAPH_ENTERPRISE_LICENSE }}
  MEMGRAPH_ORGANIZATION_NAME: ${{ secrets.MEMGRAPH_ORGANIZATION_NAME }}

jobs:
  test:
    name: "${{ inputs.test_name }} on ${{ inputs.build_name }} build"
    runs-on: [self-hosted, Linux, X64, Diff]
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull memgraph/mgbuilder:${{ github.run_id }}-${{ inputs.build_name }}
        run: docker pull $TAG

      - name: Run ${{ inputs.test_name }}
        run: |
          docker run --name ${{ inputs.test_name }}-${{ github.run_id }} \
          --rm \
          --entrypoint /bin/bash \
          $TAG -c ./docker/ci.bash test ${{ inputs.test_name }}
