name: Build Memgraph
'on':
  workflow_call:
    inputs:
      build_name:
        description: build type
        required: true
        type: string
      image_tag:
        description: image tag
        required: true
        type: string

env:
  TAG: ${{ github.event.inputs.image_tag }}

jobs:
  build:
    name: "${{ github.event.inputs.build_name }} build"
    runs-on: [self-hosted, Linux, X64, Diff]
    steps:
      - name: Set up repository
        uses: actions/checkout@v4
        with:
          # Number of commits to fetch. `0` indicates all history for all
          # branches and tags. (default: 1)
          fetch-depth: 0

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build mgbuilder image
        run: ./docker/ci.bash build ${{ github.event.inputs.build_name }}

      - name: Push memgraph/mgbuilder:$TAG
        run: docker push $TAG

      - name: Clean up
        run: docker image rm $TAG
