name: Test workflow
concurrency:
  group: ${{ github.head_ref || github.sha }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**/*.md"
      - ".clang-format"
      - "CODEOWNERS"
      - "licenses/*"

env:
  THREADS: 24
  MEMGRAPH_ENTERPRISE_LICENSE: ${{ secrets.MEMGRAPH_ENTERPRISE_LICENSE }}
  MEMGRAPH_ORGANIZATION_NAME: ${{ secrets.MEMGRAPH_ORGANIZATION_NAME }}
  OS: "debian-10"
  TOOLCHAIN_VERSION: "4"

jobs:
  build_image:
    strategy:
      fail-fast: false
      matrix:
        build_name: [community, debug, release, experimental_ha, experimental_mt]
    uses: ./.github/workflows/reusable_build.yaml
    with:
      build_name: ${{ matrix.build_name }}
      image_tag: "memgraph/mgbuilder:${{ github.run_id }}-${{ matrix.build_name }}"
      threads: 24
      os: debian-10
      toolchain_version: 4
    secrets: inherit

  #
  # test_release:
  #   name: "Test release"
  #   needs: [release_build]
  #   runs-on: [self-hosted, Linux, X64, Diff]
  #   steps:
  #     - name: Log in to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #
  #     - name: Pull mgbuilder image
  #       run: docker pull $TAG_RELEASE
  #
  # test_community:
  #   name: "Test community"
  #   needs: [community_build]
  #   runs-on: [self-hosted, Linux, X64, Diff]
  #   steps:
  #     - name: Log in to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #
  #     - name: Pull mgbuilder image
  #       run: docker pull $TAG_COMMUNITY
  #
  # test_debug:
  #   name: "Test debug"
  #   needs: [debug_build]
  #   runs-on: [self-hosted, Linux, X64, Diff]
  #   steps:
  #     - name: Log in to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #
  #     - name: Pull mgbuilder image
  #       run: docker pull $TAG_DEBUG
  #
  # test_exp_ha:
  #   name: "Test exp ha"
  #   needs: [experimental_ha_build]
  #   runs-on: [self-hosted, Linux, X64, Diff]
  #   steps:
  #     - name: Log in to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #
  #     - name: Pull mgbuilder image
  #       run: docker pull $TAG_EXP_HA
  #
  # test_exp_mt:
  #   name: "Test exp mt"
  #   needs: [experimental_build_mt]
  #   runs-on: [self-hosted, Linux, X64, Diff]
  #   steps:
  #     - name: Log in to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #
  #     - name: Pull mgbuilder image
  #       run: docker pull $TAG_EXP_MT
